CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS ad(
  id VARCHAR PRIMARY KEY,
  name VARCHAR,
  contractId VARCHAR,
  tokenId VARCHAR,
  content VARCHAR,	
  creationDate TIMESTAMP
);

CREATE TABLE IF NOT EXISTS account(
  id VARCHAR PRIMARY KEY,
  accountId VARCHAR,
  username VARCHAR
);
